[package]
name = "optika"
version = "0.1.0"
authors = ["Tom"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
euclid = "0.22.2"
bevy = "0.5.0"